# Generated by Django 5.2.17 on 2026-08-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/originales/')),
                ('texto_alt', models.CharField(blank=True, max_length=180)),
                ('principal', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imagenes de producto',
                'db_table': 'imagenes_producto',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['producto'], name='imagenes_pr_product_339785_idx'), models.Index(fields=['principal'], name='imagenes_pr_princip_fbced1_idx'), models.Index(fields=['activa'], name='imagenes_pr_activa_1f6ed1_idx')],
            },
        ),
    ]
