# Generated by Django 5.2.17 on 2026-08-16 21:54

import apps.productos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, upload_to='productos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen_web',
            field=models.ImageField(blank=True, upload_to='productos/web/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos/originales/', validators=[apps.productos.validators.validar_imagen_producto]),
        ),
    ]
