# Generated by Django 5.2.17 on 2026-08-13 21:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('canal_venta', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercado_libre', 'Mercado Libre'), ('tienda_nube', 'Tienda Nube'), ('presencial', 'Presencial')], default='whatsapp', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido',
                'verbose_name_plural': 'detalle de pedidos',
                'db_table': 'detalle_pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo'], name='pedidos_codigo_ad1c89_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_estado_b14829_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pago'], name='pedidos_estado__7da5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['canal_venta'], name='pedidos_canal_v_b8e03c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido'], name='detalle_ped_pedido__f36811_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['producto'], name='detalle_ped_product_a29678_idx'),
        ),
    ]
