# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estado", "Cambio de estado"),
                            ("estado_pago", "Cambio de estado de pago"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor_anterior", models.CharField(max_length=30)),
                ("valor_nuevo", models.CharField(max_length=30)),
                ("comentario", models.CharField(blank=True, max_length=500)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_pedido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de pedido",
                "verbose_name_plural": "eventos de pedido",
                "db_table": "eventos_pedido",
                "ordering": ["-creado_en", "-id"],
                "indexes": [
                    models.Index(
                        fields=["pedido", "creado_en"],
                        name="eventos_ped_pedido__5d6a63_idx",
                    ),
                    models.Index(
                        fields=["tipo"],
                        name="eventos_ped_tipo_4d5cd7_idx",
                    ),
                ],
            },
        ),
    ]
