# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_eventopedido"),
        ("promociones", "0002_itemcombopromocion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="promocion_aplicada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="promociones.promocion",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="promocion_nombre",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
