# Generated by Django 5.2.17 on 2026-08-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('apellido', models.CharField(blank=True, max_length=160)),
                ('razon_social', models.CharField(blank=True, max_length=180)),
                ('tipo_cliente', models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='minorista', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('documento', models.CharField(blank=True, max_length=40)),
                ('cuit', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('provincia', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ['nombre', 'apellido'],
                'indexes': [models.Index(fields=['tipo_cliente'], name='clientes_tipo_cl_8125a0_idx'), models.Index(fields=['activo'], name='clientes_activo_1f6d14_idx'), models.Index(fields=['email'], name='clientes_email_fb2cd6_idx')],
            },
        ),
    ]
