# Generated by Django 5.2.17 on 2026-08-15 13:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_promocion', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo'), ('combo', 'Combo'), ('mayorista', 'Mayorista'), ('temporada', 'Temporada'), ('envio_gratis', 'Envio gratis')], default='porcentaje', max_length=30)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compra_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('canal_venta', models.CharField(choices=[('todos', 'Todos'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('mercado_libre', 'Mercado Libre'), ('tienda_nube', 'Tienda Nube'), ('presencial', 'Presencial')], default='todos', max_length=30)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='promociones', to='productos.categoria')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'promocion',
                'verbose_name_plural': 'promociones',
                'db_table': 'promociones',
                'ordering': ['-fecha_inicio', 'nombre'],
                'indexes': [models.Index(fields=['slug'], name='promociones_slug_334821_idx'), models.Index(fields=['tipo_promocion'], name='promociones_tipo_pr_2bc7ea_idx'), models.Index(fields=['canal_venta'], name='promociones_canal_v_bcd422_idx'), models.Index(fields=['activa'], name='promociones_activa_6a93a7_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='promociones_fecha_i_a974ad_idx')],
            },
        ),
    ]
