# Generated by Django 5.2.17 on 2026-08-26

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models


def crear_items_para_combos_existentes(apps, _schema_editor):
    """Conserva combos previos usando cantidad uno por producto asociado."""
    promocion_model = apps.get_model("promociones", "Promocion")
    item_model = apps.get_model("promociones", "ItemComboPromocion")
    for promocion in promocion_model.objects.filter(tipo_promocion="combo"):
        for producto in promocion.productos.all():
            item_model.objects.get_or_create(
                promocion_id=promocion.pk,
                producto_id=producto.pk,
                defaults={"cantidad": 1},
            )


def normalizar_promociones_existentes(apps, _schema_editor):
    """Desactiva y corrige datos heredados antes de agregar restricciones."""
    promocion_model = apps.get_model("promociones", "Promocion")
    for promocion in promocion_model.objects.all():
        campos: list[str] = []
        if promocion.fecha_fin <= promocion.fecha_inicio:
            promocion.fecha_fin = promocion.fecha_inicio + timedelta(seconds=1)
            promocion.activa = False
            campos.extend(["fecha_fin", "activa"])
        if (
            promocion.porcentaje_descuento is not None
            and promocion.porcentaje_descuento <= 0
        ):
            promocion.porcentaje_descuento = None
            promocion.activa = False
            campos.extend(["porcentaje_descuento", "activa"])
        if promocion.monto_descuento is not None and promocion.monto_descuento <= 0:
            promocion.monto_descuento = None
            promocion.activa = False
            campos.extend(["monto_descuento", "activa"])
        if campos:
            promocion.save(update_fields=list(dict.fromkeys(campos)))


class Migration(migrations.Migration):

    dependencies = [("promociones", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ItemComboPromocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_combo_promocion",
                        to="productos.producto",
                    ),
                ),
                (
                    "promocion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_combo",
                        to="promociones.promocion",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de combo",
                "verbose_name_plural": "items de combo",
                "db_table": "items_combo_promocion",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["promocion"],
                        name="items_combo_promoci_a6ffe5_idx",
                    ),
                    models.Index(
                        fields=["producto"],
                        name="items_combo_product_570630_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promocion", "producto"),
                        name="combo_producto_unico",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            crear_items_para_combos_existentes,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            normalizar_promociones_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="promocion",
            constraint=models.CheckConstraint(
                condition=models.Q(fecha_fin__gt=models.F("fecha_inicio")),
                name="promocion_fecha_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocion",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(porcentaje_descuento__isnull=True)
                    | models.Q(porcentaje_descuento__gt=0)
                ),
                name="promocion_porcentaje_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="promocion",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(monto_descuento__isnull=True)
                    | models.Q(monto_descuento__gt=0)
                ),
                name="promocion_monto_positivo",
            ),
        ),
    ]
